# Generated by Django 5.0.3 on 2024-06-23 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0003_alter_category_id_alter_customer_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrdouctGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mobile_app.product')),
            ],
            options={
                'verbose_name': 'Product gallery',
                'verbose_name_plural': 'Product gallery',
            },
        ),
    ]
